version: '3'

volumes:
    db:
    registry:

services:
    db:
        image: "mariadb:latest"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=portus
            - MYSQL_USER=portus
            - MYSQL_PASSWORD=portus
        volumes:
            - db:/var/lib/mysql:rw
        ports:
            - "3306:3306"

    portus:
        image: "stargate01/portus:latest"
        build: .
        restart: always
        volumes:
            - ./config/certs/privkey.pem:/opt/certs/privkey.pem:ro
        env_file:
            - ./config/portus.env
        ports:
            - "3000:3000"

    portus-bg:
        image: "stargate01/portus:latest"
        build: .
        restart: always
        volumes:
            - ./config/certs/privkey.pem:/opt/certs/privkey.pem:ro
        env_file:
            - ./config/portus.env
        environment:
            - PORTUS_BACKGROUND=true

    registry:
        image: "registry:latest"
        volumes:
            - registry:/data:rw
            - ./config/certs/certificate.pem:/opt/certs/certificate.pem:ro
        restart: always
        env_file:
            - ./config/registry.env
        environment: 
            REGISTRY_NOTIFICATIONS_ENDPOINTS: >
                - name: portus
                  url: http://portus.home:3000/v2/webhooks/events
                  timeout: 2000ms
                  threshold: 5
                  backoff: 10s
        ports:
            - "5000:5000"